name: Event_Filters
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'releases/*'
    # Sequence of patterns matched against refs/tags
    tags:
      - v1.*

jobs:
  linux-os:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
